package com.dd.music


object Constant {
    const val HOMEPAGE_SLIDE_PLAYLIST = "HOMEPAGE_SLIDE_PLAYLIST"
    const val HOMEPAGE_SLIDE_SONGLIST_ALIGN = "HOMEPAGE_SLIDE_SONGLIST_ALIGN"
    const val HOMEPAGE_BANNER = "HOMEPAGE_SLIDE_SONGLIST_ALIGN"
}